Fixes UndefinedFunctionError in show_vars task
Shimmur/env_var_provider pull request #26
Opened 2020-06-18 03:08 UTC by sabondano

Why:

* Running `mix show_vars ''` was returning

```
** (UndefinedFunctionError) function EnvVar.Config.config/0 is undefined
(module EnvVar.Config is not available)
    EnvVar.Config.config()
    lib/providers/env_var_provider.ex:140: EnvVar.Provider.show_vars/1
    (mix 1.10.3) lib/mix/task.ex:330: Mix.Task.run_task/3
    (mix 1.10.3) lib/mix/cli.ex:82: Mix.CLI.run_task/2
```

2020-06-18 03:25 UTC, sabondano commented
whoops, but this line was removed in this previous commit 🤔 . Maybe by mistake? Or did we have another plan for making sure the target module is compiled? https://github.com/Shimmur/env_var_provider/commit/eb7b92a56fcacddc9bf8d2c815167cc25f0fc97e

2020-06-18 08:37 UTC, whatyouhide commented
I can't see why I would remove the call to `mix compile`, so let's re-add it, but please can you bump the patch version in `mix.exs` too, update the CHANGELOG, and the usual release shenanigans? Thanks!

2020-06-18 08:38 UTC, whatyouhide requested changes
Messed up leaving a review, but this is blocking until we can bump the release as described in my comment.

2020-06-18 21:48 UTC, sabondano commented
> Messed up leaving a review, but this is blocking until we can bump the release as described in my comment.

- bumped version ✅ 
- added and updated changelog ✅  (I assume this is cool but let  me know if you think we shouldn't have one for some reason and I can remove it)

2020-06-18 21:51 UTC, JoeMerriweather-Webb approved these changes

2020-06-22 08:38 UTC, whatyouhide approved these changes
⚠️ IMPORTANT ⚠️ : you will have to do `mix hex.publish --organization community` otherwise you'll publish this under your own Hex account.

2020-06-22 08:38 UTC, whatyouhide commented on CHANGELOG.md
> +  - Ensures source module is compiled before the mix `show_vars` task runs.
```suggestion
  - Ensures project is compiled before the mix `show_vars` task runs.
```

2020-06-22 17:46 UTC, merged